local PLUGIN_NAME<const> = "AnimatedInteractions" -- dll name
local AUTHOR_NAME<const> = "Monitor144hz"
local DESCRIPTION<const> = ""
local VERSION<const> = "1.8.1"
local LICENSE<const> = "" -- FIXME: MIT OR Apache-2.0 ?
--

-- Global settings
set_arch("x64")
set_encodings("utf-8")
set_warnings("allextra")

add_rules("mode.debug", "mode.releasedbg")
set_defaultmode("releasedbg")

-- deps
set_config("rex_ini", true)
includes("extern/CommonLibSSE_NG")

target(PLUGIN_NAME, function ()
    set_languages("cxx23")
    set_kind("shared")

    add_deps("commonlibsse-ng")

    add_headerfiles("src/**.h")
    set_pcxxheader("src/PCH.h")
    add_files("src/**.cpp")

    -- on_install: SKSE/Plugins/<PLUGIN_NAME>/<PLUGIN_NAME>.dll
    set_version(VERSION)
    set_license(LICENSE)
    add_rules("commonlibsse-ng.plugin", {
        name = PLUGIN_NAME,
        author = AUTHOR_NAME,
        description = DESCRIPTION,
    })

    -- NOTE: Copying `Data` contents individually into the install directory
    -- prevents unintentionally overwriting/removing the DLL generated by `"commonlibsse-ng.plugin"`.
    after_install(function (target)
        local installdir = target:installdir()

        for _, file in ipairs(os.files("assets/Data/**")) do
            local rel = path.relative(file, "assets/Data")
            os.cp(file, path.join(installdir, rel))
        end
    end)
end)
